/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:170adccb-e199-463f-9699-cc1d5fb385c0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_rfDsAq8oP",
    "aws_user_pools_web_client_id": "2kq5puj2mo2040dnopkfkiv7ej",
    "oauth": {}
};


export default awsmobile;
